SnapdragonLauncher: fix bug for ClassCastException
Description:
java.lang.ClassCastException: com.android.launcher3.BubbleTextView
cannot be cast to com.android.launcher3.CellLayout.
Hotseat had been redesigned and base structure change from CellLayout
to LinearLayout.

Change-Id: I83f601b642ddb16abbab4b8676928317be2d53bb
CRs-Fixed: 1058108